name: Slack Pull Request Open Notification

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up environment variables
        run: |
          echo "GITHUB_TO_SLACK_MAPPING=cson2701:U03L252MT0T" >> $GITHUB_ENV

      - name: Extract GitHub username
        id: extract_username
        run: echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Find Slack user ID
        id: find_slack_user
        run: echo "slack_id=$(echo $GITHUB_TO_SLACK_MAPPING | grep -oP "${{ github.event.pull_request.user.login }}:\K[^,]+")" >> $GITHUB_OUTPUT

      - name: Send message to Slack
        id: slack
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C03KMJQ53EK
          slack-text: New pull request to review by *${{ github.event.pull_request.user.login }}* <@${{ steps.find_slack_user.outputs.slack_id }}>:\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}

      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.slack.outputs.slack-result }}"
